"""
Fall Fest 2026 Challenge - Grading Functions
"""
from qc_grader.grader.grade import create_check_progress_function

from .intro import (
    grade_intro_ex1,
    grade_intro_ex2,
    grade_intro_ex3,
    grade_intro_ex4,
    grade_intro_ex5,
    grade_intro_ex6,
    grade_intro_ex7,
    grade_intro_ex8,
    grade_intro_ex9,
    grade_intro_ex10,
    grade_intro_ex11,
    grade_intro_ex12,
    grade_intro_ex13,
    grade_intro_ex14,
)

from .dj import (
    grade_dj_ex1,
    grade_dj_ex2,
    grade_dj_ex3,
    grade_dj_ex4,
    grade_dj_ex5,
    grade_dj_ex6,
    grade_dj_ex7,
    grade_dj_ex8,
    grade_dj_ex9,
)

from .qkd import (
    grade_qkd_ex1,
    grade_qkd_ex2,
    grade_qkd_ex3,
    grade_qkd_ex4,
    grade_qkd_ex5,
    grade_qkd_ex6,
    grade_qkd_ex7,
    grade_qkd_ex8,
    grade_qkd_ex9,
)

from .teleport import (
    grade_teleport_ex1,
    grade_teleport_ex2,
    grade_teleport_ex3,
    grade_teleport_ex4,
    grade_teleport_ex5,
    grade_teleport_ex6,
    grade_teleport_ex7,
    grade_teleport_ex8,
    grade_teleport_ex9,
)

from .qft import (
    grade_qft_ex1,
    grade_qft_ex2,
    grade_qft_ex3,
    grade_qft_ex4,
    grade_qft_ex5,
    grade_qft_ex6,
    grade_qft_ex7,
    grade_qft_ex8,
    grade_qft_ex9,
    grade_qft_ex10,
    grade_qft_ex11,
)

from .shors import (
    grade_shors_ex1,
    grade_shors_ex2,
    grade_shors_ex3,
    grade_shors_ex4,
    grade_shors_ex5,
    grade_shors_ex6,
    grade_shors_ex7,
    grade_shors_ex8,
    grade_shors_ex9,
    grade_shors_ex10,
)

from .vqe import (
    grade_vqe_ex1,
    grade_vqe_ex2,
    grade_vqe_ex3,
    grade_vqe_ex4,
    grade_vqe_ex5,
    grade_vqe_ex6,
    grade_vqe_ex7,
    grade_vqe_ex8,
    grade_vqe_ex9,
    grade_vqe_ex10,
    grade_vqe_ex11,
    grade_vqe_ex12,
)

from .bell import (
    grade_bell_ex1,
    grade_bell_ex2,
    grade_bell_ex3,
    grade_bell_ex4,
    grade_bell_ex5,
    grade_bell_ex6,
    grade_bell_ex7,
    grade_bell_ex8,
    grade_bell_ex9,
    grade_bell_ex10,
    grade_bell_ex11,
    grade_bell_ex12,
    grade_bell_ex13,
    grade_bell_ex14,
    grade_bell_ex15,
    grade_bell_ex16,
    grade_bell_ex17,
    grade_bell_ex18,
)

from .uncertainty import (
    grade_uncertainty_ex1,
    grade_uncertainty_ex2,
    grade_uncertainty_ex3,
    grade_uncertainty_ex4,
    grade_uncertainty_ex5,
    grade_uncertainty_ex6,
    grade_uncertainty_ex7,
    grade_uncertainty_ex8,
    grade_uncertainty_ex9,
    grade_uncertainty_ex10,
    grade_uncertainty_ex11,
)

from .sg import (
    grade_sg_ex1,
    grade_sg_ex2,
    grade_sg_ex3,
    grade_sg_ex4,
    grade_sg_ex5,
    grade_sg_ex6,
    grade_sg_ex7,
    grade_sg_ex8,
    grade_sg_ex9,
    grade_sg_ex10,
    grade_sg_ex11,
)

from .superposition import (
    grade_superposition_ex1,
    grade_superposition_ex2,
    grade_superposition_ex3,
    grade_superposition_ex4,
    grade_superposition_ex5,
    grade_superposition_ex6,
    grade_superposition_ex7,
    grade_superposition_ex8,
)

from .grovers import (
    grade_grovers_ex1,
    grade_grovers_ex2,
    grade_grovers_ex3,
    grade_grovers_ex4,
    grade_grovers_ex5,
    grade_grovers_ex6,
    grade_grovers_ex7,
    grade_grovers_ex8,
)

_CHALLENGE = 'fallfest_2026'
check_progress = create_check_progress_function(_CHALLENGE)
__all__ = [
    'check_progress',
    'grade_intro_ex1',
    'grade_intro_ex2',
    'grade_intro_ex3',
    'grade_intro_ex4',
    'grade_intro_ex5',
    'grade_intro_ex6',
    'grade_intro_ex7',
    'grade_intro_ex8',
    'grade_intro_ex9',
    'grade_intro_ex10',
    'grade_intro_ex11',
    'grade_intro_ex12',
    'grade_intro_ex13',
    'grade_intro_ex14',
    'grade_dj_ex1',
    'grade_dj_ex2',
    'grade_dj_ex3',
    'grade_dj_ex4',
    'grade_dj_ex5',
    'grade_dj_ex6',
    'grade_dj_ex7',
    'grade_dj_ex8',
    'grade_dj_ex9',
    'grade_qkd_ex1',
    'grade_qkd_ex2',
    'grade_qkd_ex3',
    'grade_qkd_ex4',
    'grade_qkd_ex5',
    'grade_qkd_ex6',
    'grade_qkd_ex7',
    'grade_qkd_ex8',
    'grade_qkd_ex9',
    'grade_teleport_ex1',
    'grade_teleport_ex2',
    'grade_teleport_ex3',
    'grade_teleport_ex4',
    'grade_teleport_ex5',
    'grade_teleport_ex6',
    'grade_teleport_ex7',
    'grade_teleport_ex8',
    'grade_teleport_ex9',
    'grade_qft_ex1',
    'grade_qft_ex2',
    'grade_qft_ex3',
    'grade_qft_ex4',
    'grade_qft_ex5',
    'grade_qft_ex6',
    'grade_qft_ex7',
    'grade_qft_ex8',
    'grade_qft_ex9',
    'grade_qft_ex10',
    'grade_qft_ex11',
    'grade_shors_ex1',
    'grade_shors_ex2',
    'grade_shors_ex3',
    'grade_shors_ex4',
    'grade_shors_ex5',
    'grade_shors_ex6',
    'grade_shors_ex7',
    'grade_shors_ex8',
    'grade_shors_ex9',
    'grade_shors_ex10',
    'grade_vqe_ex1',
    'grade_vqe_ex2',
    'grade_vqe_ex3',
    'grade_vqe_ex4',
    'grade_vqe_ex5',
    'grade_vqe_ex6',
    'grade_vqe_ex7',
    'grade_vqe_ex8',
    'grade_vqe_ex9',
    'grade_vqe_ex10',
    'grade_vqe_ex11',
    'grade_vqe_ex12',
    'grade_bell_ex1',
    'grade_bell_ex2',
    'grade_bell_ex3',
    'grade_bell_ex4',
    'grade_bell_ex5',
    'grade_bell_ex6',
    'grade_bell_ex7',
    'grade_bell_ex8',
    'grade_bell_ex9',
    'grade_bell_ex10',
    'grade_bell_ex11',
    'grade_bell_ex12',
    'grade_bell_ex13',
    'grade_bell_ex14',
    'grade_bell_ex15',
    'grade_bell_ex16',
    'grade_bell_ex17',
    'grade_bell_ex18',
    'grade_uncertainty_ex1',
    'grade_uncertainty_ex2',
    'grade_uncertainty_ex3',
    'grade_uncertainty_ex4',
    'grade_uncertainty_ex5',
    'grade_uncertainty_ex6',
    'grade_uncertainty_ex7',
    'grade_uncertainty_ex8',
    'grade_uncertainty_ex9',
    'grade_uncertainty_ex10',
    'grade_uncertainty_ex11',
    'grade_sg_ex1',
    'grade_sg_ex2',
    'grade_sg_ex3',
    'grade_sg_ex4',
    'grade_sg_ex5',
    'grade_sg_ex6',
    'grade_sg_ex7',
    'grade_sg_ex8',
    'grade_sg_ex9',
    'grade_sg_ex10',
    'grade_sg_ex11',
    'grade_superposition_ex1',
    'grade_superposition_ex2',
    'grade_superposition_ex3',
    'grade_superposition_ex4',
    'grade_superposition_ex5',
    'grade_superposition_ex6',
    'grade_superposition_ex7',
    'grade_superposition_ex8',
    'grade_grovers_ex1',
    'grade_grovers_ex2',
    'grade_grovers_ex3',
    'grade_grovers_ex4',
    'grade_grovers_ex5',
    'grade_grovers_ex6',
    'grade_grovers_ex7',
    'grade_grovers_ex8']
