name: CI

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.10"
      - uses: extractions/setup-just@v3
      - name: install
        run: uv sync --all-extras
      - run: just lint
      - run: just test
